# Admin Password (MUST BE AT THE TOP)
admin_password = "Anonymous_77"

# Email
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "justinsaju100@gmail.com"
sender_password = "znja mgek ksho hwdg"

# Google Sheets
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1GA6TMom4CouSNFEesCEANqe3ZtP2MKk4d9PfsTXmPRQ/edit#gid=0"
type = "service_account"
project_id = "aqueous-impact-482618-q9"
private_key_id = "2d873543b6e989b1f36e1ea16c4bd31b6ba1a191"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOIHjPd0cYtYEm
IeyxbzucO4v0Lx3Ay/XFEXMCFrK2wtTDFSI6TOalKbJYaeIIoY5v+zeJVzKY+TWn
oubV/bPZW805CHIeNN68AKo+Mm7PbRbGJ9osmcao5fp5RhRB//vPW69FsXyy7P36
1B7wYe7KgcYxo8vsESJHpxVczJllxZBtQOAOVoqdJ0M9LgBKewFWp87R1MwxnCcL
K7ohAABXGi2QyoLOa+mdukRcrUE0fXERYT71MCx+oscUX7IRi1T0VRqZp0jkE+d2
QGCk7AiT3MCxJ/SgrSu4pq54W5PrT3LV2vyFY4Olgest9hM/mwhy2UinaMGQzgx/
i948Jz3jAgMBAAECggEAGdtO7E99FqdmDP+CbnuSkbWSh84FQHMVYGQg9ikcv/pO
sC4Nfhy5bgx998NIfGavtHJh9BOBIFlalq3DoSJTFjgC1V2u2wUsz46RzH2NEu4P
RkonfyLHHdbDhcT5s5HF56wLn4V1LAi4j2defi76wmJnF0EBypoXn79g2aQ8tdxJ
3pTcsLJGkUWKcI8zMXQWj1peNSPyxdiIbjTWAWwOMw9ucwpvZ7IZXAiN1DKsIhOa
sRn3xDcpFO2B84VhhPWD1UezEXx7i+UKoHj+E5w3n3qZczoN7EUlm+uv8nXlbtvO
LWlSs2vUyXAhxk8mq+6aC05xt7lXyKHQrprV6BCgkQKBgQDxeyZbwQKLMRgrvB2Z
3hUyPQHhI42DyUOWF9J2UN5fFR2MaRzuSK99OD+S4fSvNK12BdnRNNaC/GLAwgGi
fm9EAZ+tr5V4Ag84ho3hXYT+ZZ7MwnJUDGu/h9V8VylikViqszRXg5Kn/i8RKohB
ngIghjtUkx2cUsmh4IAth5/2yQKBgQDahSdmc+lOAHe6/BvGGHee2dhTheqdFUFr
ty2pocsiq8e1CeGB5ZGK0NoUI0vJ7yEzSui2pNMw/sJ5EiWaapCJD38TYbj5IoWG
AK4m0r5pIp600Uw+4jI67Oxak1v8U/pMqNENrQF18VhrREOn/qpgSEb6tPESzuxN
9akOAMXpSwKBgFvyYkaplUhepy9v7215DGUWqbKKEQZPCjcKVw7J+AIITjn6hBOP
BZMOadaJxts3mZzI2Yk5Lzys0QVIWcr/jWo9nAlMRANv9U+2nCtlqpAbLX4Vw+aQ
3C4PkJBJt+5aHYLRvWpdJOhmdpF4um0RtwmfUtP/OFUfiLrkeqnbbGNRAoGAcssY
U534pd1hCH2AKaSY0n4mQlpLUZHk+C0Wc9Jm4CPVmalDKfXraz0kEwgnvEE+868a
aThVKZvrlaaO0nvAyf+2BfyEK3yTID4jPonfNWPWc66vmylAsevcjghzfi6vgq38
hG6qIcdTZ6ZI1GvYHRRbFUEQk4zYXmv7Dzwgu9kCgYEA4j/JUPeNfFgt6WI/tC02
JKbHMLHVuJnY+f3jFj3XOnh5CKgBDz1KsUVXdZ6ese9R5eDIXdIhnETqtyJM60Hm
9rarSH6sqchhp6lJ4nYBHvlqwKvnMF0ToAze0NfW4i+KKP0sCoBAYIFWyeI7hkPW
iB/Nf/DQJzWYkpiiu/ohat0=
-----END PRIVATE KEY-----"""
client_email = "print-app-manager@aqueous-impact-482618-q9.iam.gserviceaccount.com"
client_id = "114284650769194697287"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/print-app-manager%40aqueous-impact-482618-q9.iam.gserviceaccount.com"
